import { SignInButton, SignOutButton, useAuth, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { userId, sessionId, getToken } = useAuth();
  const { isLoaded, isSignedIn, user } = useUser();
  console.log({ isLoaded, isSignedIn, user, userId, sessionId });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {isSignedIn ? (
          <SignOutButton>
            <span className="text-gray-200">Sign me out!</span>
          </SignOutButton>
        ) : (
          <SignInButton>
            <span className="text-gray-200">Sign me in!</span>
          </SignInButton>
        )}
      </main>
    </>
  );
};

export default Home;
